version: '3.8'

services:
  app:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
    networks:
      - workspace
    volumes:
      - ..:/app
      - ssh-keys:/root/.ssh
    # Set services env variables
    env_file:
      - ../.env
    # Set workspace env variables
    environment:
      - ZDOTDIR=/app/.dotfiles
      - PYTHONPATH=:/code
      # - RDS_DB_NAME=development_db
      # - RDS_USERNAME=root
      # - RDS_PASSWORD=root
      # - RDS_HOSTNAME=mysql
      # - RDS_PORT=3306

networks:
  workspace:
    
volumes:
  ssh-keys:
