alias test='python /app/src/manage.py test'
alias freeze='pip freeze > /app/requirements.txt'
alias migrate='python /app/src/manage.py migrate'
alias runserver='python /app/src/manage.py runserver 8080'
alias check='python /app/src/manage.py check'
alias manage='python /app/src/manage.py'